---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-eks-a
  namespace: hello-eks
  labels:
    app: hello-eks-a
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-eks-a
  template:
    metadata:
      labels:
        app: hello-eks-a
    spec:
      containers:
      - name: hello
        image: public.ecr.aws/aws-containers/hello-eks-anywhere:latest
        ports:
        - containerPort: 80
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: hello-eks-a
  namespace: hello-eks
spec:
  type: NodePort
  selector:
    app: hello-eks-a
  ports:
    - port: 80
---
#uj

#ingress internet facing
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  namespace: hello-eks
  name: ingress-hello-eks
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS":443}, {"HTTP":80}]'
#    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:eu-central-1:309362968926:certificate/f98eb79f-1bf0-4727-9af5-99edf065511c
spec:
  rules:
    - http:
        paths:
          - path: /*
            backend:
              serviceName: hello-eks-a
              servicePort: 80
